version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: watchtower-storage
    ports:
      - "9000:9000"   # Port untuk API S3 (diakses oleh aplikasi Go)
      - "9001:9001"   # Port untuk Web Console (diakses lewat browser)
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  minio_data:

# Menggunakan MinIO, repository open-source yang kompatibel dengan AWS S3 dan dijalankan lokal menggunakan docker